### ISSUE TITLE
renaming things for no reason breaks stuff

### ISSUE THREAD

**Issue by stephenmathieson** [gohttp/jsonrpc-client#7]
@vinceprignano 

why did we rename "mock -> rpcmock" ?

**Comment by f2prateek** [comment]
@stephenmathieson  I think it was to avoid collisions with other packages that have a `mock` package so things just work out of the box and you don't have to manually namespace, plus the convention that you'd do `mock := mock.NewClient()`

**Comment by stephenmathieson** [comment]
@f2prateek it's been awhile, but I think the issue here was we don't have semver (hooray golang), so we should have avoided pushing breaking changes

NBD tho, closing
